spring:
  application:
    name: unit-testing
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console:
      enabled: true

server:
  port: 8100